---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-controller
spec:
  replicas: 1
  selector:
    app: kafka-controller
  template:
    metadata:
      labels:
        app: kafka-controller
    spec:
      containers:
        - name: kafka-controller
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: 100.65.242.37
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zoo1:2181,zoo2:2181